### ISSUE TITLE
SZ todo list

### ISSUE THREAD

**Issue by phaustin** [phaustin/a448#5]
Project todo list for Shuting

- [ ] Clone https://github.com/pangeo-data/pangeo-cmip6-examples
- [ ] go over the  [cmip6 tutorial](https://medium.com/pangeo/cmip6-in-the-cloud-five-ways-96b177abe396)
- [ ] fix issue #10 pangeo
- [ ] Check (ModuleNotFoundError: No module named 'dask_kubernetes')
