### ISSUE TITLE
EW todo list

### ISSUE THREAD

**Issue by phaustin** [phaustin/a448#6]
Task list for watershed/burn index projects

- [ ] First satpy tutorial and put before and after geotiffs into satpy xarray
- [ ] Satpy resample to resample both images on the same grid
- [ ] Qualitative/quantitative check on how good the burn ratio did.
- [ ] cloud masking
- [ ] compare two different channel

**Comment by phaustin** [comment]
https://github.com/pytroll/tutorial-satpy-half-day/tree/master/notebooks
https://developers.google.com/earth-engine/python_install
